# Generated by Django 5.0.7 on 2024-08-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='current_time',
        ),
        migrations.AlterField(
            model_name='favoritesong',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='tracking.song', verbose_name='Şarkılar'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='song',
            field=models.CharField(default='Bilinmeyen Şarkı', max_length=255, verbose_name='Şarkı'),
            preserve_default=False,
        ),
    ]
