# Generated by Django 5.0.7 on 2024-08-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_useractivity_current_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='current_track_title',
            field=models.CharField(default='Bilinmeyen Başlık', max_length=255, verbose_name='Şarkı Başlığı'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='song',
            field=models.CharField(default='Bilinmeyen Şarkı', max_length=255, verbose_name='Şarkı'),
        ),
    ]
