# Generated by Django 5.0.7 on 2024-08-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_rename_user_id_useractivity_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='songs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
