# Generated by Django 5.0.7 on 2024-08-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
