# Generated by Django 5.0.7 on 2024-08-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_useractivity_current_track_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='current_track_title',
        ),
    ]
