# Generated by Django 5.0.7 on 2024-08-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_remove_useractivity_current_track_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='current_time',
            field=models.CharField(default='00:00', max_length=10, verbose_name='Şu Anki Zaman'),
        ),
    ]
