# Generated by Django 5.0.7 on 2024-08-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='interval',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
