# Generated by Django 5.0.7 on 2024-08-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_alter_song_options_alter_song_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mağaza Adı'),
        ),
    ]
