# Generated by Django 5.0.7 on 2024-08-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_useractivity_is_active_alter_useractivity_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktif mi?'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='store_name',
            field=models.CharField(default='Bilinmeyen Mağaza', max_length=255, verbose_name='Mağaza Adı'),
            preserve_default=False,
        ),
    ]
