# Generated by Django 5.0.7 on 2024-08-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_useractivity_current_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='current_time',
            field=models.CharField(default='00:00', max_length=10, verbose_name='Şu Anki Süre'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='last_active',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Aktivite'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.song', verbose_name='Şarkı'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='store_name',
            field=models.CharField(max_length=255, verbose_name='Mağaza Adı'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Zaman Damgası'),
        ),
    ]
