# Generated by Django 5.0.7 on 2024-08-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_alter_useractivity_current_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='current_time',
            field=models.CharField(default='00:00', max_length=10, verbose_name='Şu Anki Zaman'),
        ),
    ]
